import { Module } from '@nestjs/common';
import { Episode, EpisodeSchema } from '../episodes/schemas/episode.schema';
import { MongooseModule } from '@nestjs/mongoose';
import {
  ActivityType,
  ActivityTypeSchema,
  ActivityTypesSchema,
  MultiChoiceQuestionSchema,
  FillInTheBlanksSchema,
  CardMatchSchema,
  CategorizeItSchema,
  PhotoMatchSchema,
  TranslationMatchSchema,
  ListMatchSchema,
  WordDiscoverySchema,
  MazeGameSchema,
  CrosswordPuzzleSchema,
  QAShortAnswerSchema,
  ReflectRespondSchema,
  MultiAnswerShortQASchema,
  HandsOnActivitySchema,
  FreeDrawingSchema,
  DynamicOrderBlanksSchema,
  CompleteTheShapeSchema,
  LocateItSchema,
  FillTheKabahSchema,
  FillTheColorSchema,
  UserActivityProgressSchema,
} from './schemas';
import {
  ActivityTypesService,
  MultiChoiceQuestionsService,
  FillInTheBlanksService,
  CardMatchService,
  CategorizeItService,
  PhotoMatchService,
  TranslationMatchService,
  ListMatchService,
  WordDiscoveryService,
  MazeGameService,
  CrosswordPuzzleService,
  QAShortAnswerService,
  ReflectRespondService,
  MultiAnswerShortQAService,
  HandsOnActivityService,
  FreeDrawingService,
  DynamicOrderBlanksService,
  CompleteTheShapeService,
  LocateItService,
  FillTheKabahService,
  FillTheColorService,
  UserActivityProgressService,
} from './services';
import {
  ActivityTypesController,
  MultiChoiceQuestionsController,
  FillInTheBlanksController,
  CardMatchController,
  CategorizeItController,
  PhotoMatchController,
  TranslationMatchController,
  ListMatchController,
  WordDiscoveryController,
  MazeGameController,
  CrosswordPuzzleController,
  QAShortAnswerController,
  ReflectRespondController,
  MultiAnswerShortQAController,
  HandsOnActivityController,
  FreeDrawingController,
  DynamicOrderBlanksController,
  CompleteTheShapeController,
  LocateItController,
  FillTheKabahController,
  FillTheColorController,
  UserActivityProgressController,
} from './controllers';

@Module({
  imports: [
    MongooseModule.forFeature([
      { name: ActivityType.name, schema: ActivityTypeSchema },
      { name: 'MultiChoiceQuestion', schema: MultiChoiceQuestionSchema },
      { name: 'FillInTheBlanks', schema: FillInTheBlanksSchema },
      { name: 'CardMatch', schema: CardMatchSchema },
      { name: 'CategorizeIt', schema: CategorizeItSchema },
      { name: 'PhotoMatch', schema: PhotoMatchSchema },
      { name: 'TranslationMatch', schema: TranslationMatchSchema },
      { name: 'ListMatch', schema: ListMatchSchema },
      { name: 'WordDiscovery', schema: WordDiscoverySchema },
      { name: 'MazeGame', schema: MazeGameSchema },
      { name: 'CrosswordPuzzle', schema: CrosswordPuzzleSchema },
      { name: 'QAShortAnswer', schema: QAShortAnswerSchema },
      { name: 'ReflectRespond', schema: ReflectRespondSchema },
      { name: 'MultiAnswerShortQA', schema: MultiAnswerShortQASchema },
      { name: 'HandsOnActivity', schema: HandsOnActivitySchema },
      { name: 'FreeDrawing', schema: FreeDrawingSchema },
      { name: 'DynamicOrderBlanks', schema: DynamicOrderBlanksSchema },
      { name: 'CompleteTheShape', schema: CompleteTheShapeSchema },
      { name: 'LocateIt', schema: LocateItSchema },
      { name: 'FillTheKabah', schema: FillTheKabahSchema },
      { name: 'FillTheColor', schema: FillTheColorSchema },
      { name: 'UserActivityProgress', schema: UserActivityProgressSchema },
      { name: Episode.name, schema: EpisodeSchema },
    ]),
  ],
  providers: [
    ActivityTypesService,
    MultiChoiceQuestionsService,
    FillInTheBlanksService,
    CardMatchService,
    CategorizeItService,
    PhotoMatchService,
    TranslationMatchService,
    ListMatchService,
    WordDiscoveryService,
    MazeGameService,
    CrosswordPuzzleService,
    QAShortAnswerService,
    ReflectRespondService,
    MultiAnswerShortQAService,
    HandsOnActivityService,
    FreeDrawingService,
    DynamicOrderBlanksService,
    CompleteTheShapeService,
    LocateItService,
    FillTheKabahService,
    FillTheColorService,
    UserActivityProgressService,
  ],
  controllers: [
    ActivityTypesController,
    MultiChoiceQuestionsController,
    FillInTheBlanksController,
    CardMatchController,
    CategorizeItController,
    PhotoMatchController,
    TranslationMatchController,
    ListMatchController,
    WordDiscoveryController,
    MazeGameController,
    CrosswordPuzzleController,
    QAShortAnswerController,
    ReflectRespondController,
    MultiAnswerShortQAController,
    HandsOnActivityController,
    FreeDrawingController,
    DynamicOrderBlanksController,
    CompleteTheShapeController,
    LocateItController,
    FillTheKabahController,
    FillTheColorController,
    UserActivityProgressController,
  ],
  exports: [
    ActivityTypesService,
    MultiChoiceQuestionsService,
    FillInTheBlanksService,
    CardMatchService,
    CategorizeItService,
    PhotoMatchService,
    TranslationMatchService,
    ListMatchService,
    WordDiscoveryService,
    MazeGameService,
    CrosswordPuzzleService,
    QAShortAnswerService,
    ReflectRespondService,
    MultiAnswerShortQAService,
    HandsOnActivityService,
    FreeDrawingService,
    DynamicOrderBlanksService,
    CompleteTheShapeService,
    LocateItService,
    FillTheKabahService,
    FillTheColorService,
    UserActivityProgressService,
  ],
})
export class ActivitiesModule {}
